name: Exceletor

# Questo workflow viene attivato con i push nel repository.
on:
  push:
    branches:
      - main  # Cambia 'master' in 'main' se il tuo branch principale è 'main'

jobs:
  build:
    # Questo job verrà eseguito su una macchina virtuale Ubuntu
    runs-on: ubuntu-latest
    steps:
    
      # Checkout del codice
      - uses: actions/checkout@v3
      
      # Imposta l'ambiente Java per costruire l'app Android
      - uses: actions/setup-java@v3
        with:
          java-version: '17'  # Versione di Java da utilizzare (17.x è già coperta da '17')
      
      # Imposta l'ambiente Flutter
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'  # 'dev', 'alpha', o 'stable'
      
      # Ottieni le dipendenze Flutter
      - run: flutter pub get
      
      # Controlla eventuali problemi di formattazione
      - run: flutter format --set-exit-if-changed .
      
      # Analizza staticamente il codice Dart per errori
      - run: flutter analyze .
      
      # Esegui i test dei widget
      - run: flutter test
      
      # Compila l'APK
      - run: flutter build apk --release  # Specifica l'opzione --release per costruire l'APK di produzione
      
      # Carica l'APK generato come artifact
      - uses: actions/upload-artifact@v2
        with:
          name: release-apk
          path: build/app/outputs/flutter-apk/app-release.apk  # Assicurati che il percorso sia corretto
