name: Build & Release for Desktop

on:
  push:
    branches:
      - main
      - develop

jobs:
  build-desktop:
    name: Build Desktop Apps
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [windows-latest, ubuntu-latest, macos-latest]
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          architecture: x64

      # Install dependencies for Linux
      - if: matrix.platform == 'ubuntu-latest'
        run: |
          sudo apt-get update -y
          sudo apt-get install -y ninja-build libgtk-3-dev

      # Build Flutter app for each platform
      - run: |
          if [[ "${{ matrix.platform }}" == 'ubuntu-latest' ]]; then
            flutter build linux --release;
          elif [[ "${{ matrix.platform }}" == 'macos-latest' ]]; then
            flutter build macos --release;
          else
            flutter build windows --release;
          fi

  release:
    name: Release Desktop Artifacts
    runs-on: ubuntu-latest
    needs: build-desktop
    steps:
      - uses: actions/checkout@v4
      - name: Push to Releases
        uses: ncipollo/release-action@v1
        with:
          artifacts: |
            build/linux/x64/release/bundle/*,
            build/macos/Build/Products/Release/*.app,
            build/windows/x64/Release/*.exe
          tag: v1.0.${{ github.run_number }}
          token: ${{ secrets.TRY_EXCELETOR_TOKEN }}
