name: "Desktop Build & Release"

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  build-linux:
    name: Build Linux
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
      - name: Install Linux Dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y ninja-build libgtk-3-dev
      - name: Install project dependencies
        run: flutter pub get
      - name: Build Linux
        run: flutter build linux --release
      - name: Archive Linux Build
        uses: actions/upload-artifact@v3
        with:
          name: linux-build
          path: build/linux/x64/release/bundle/

  build-windows:
    name: Build Windows
    runs-on: windows-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
      - name: Install project dependencies
        run: flutter pub get
      - name: Build Windows
        run: flutter build windows --release
      - name: Archive Windows Build
        uses: actions/upload-artifact@v3
        with:
          name: windows-build
          path: build/windows/x64/runner/Release/

  build-macos:
    name: Build macOS
    runs-on: macos-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
      - name: Install project dependencies
        run: flutter pub get
      - name: Build macOS
        run: flutter build macos --release
      - name: Archive macOS Build
        uses: actions/upload-artifact@v3
        with:
          name: macos-build
          path: build/macos/Build/Products/Release/

  release:
    name: Release Desktop Artifacts
    runs-on: ubuntu-latest
    needs: [build-linux, build-windows, build-macos]
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: linux-build
          path: ./builds/linux
      - uses: actions/download-artifact@v3
        with:
          name: windows-build
          path: ./builds/windows
      - uses: actions/download-artifact@v3
        with:
          name: macos-build
          path: ./builds/macos
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ./builds/linux/**
            ./builds/windows/**
            ./builds/macos/**
          tag_name: desktop-v1.0.${{ github.run_number }}
        env:
          GITHUB_TOKEN: ${{ secrets.TRY_EXCELETOR_TOKEN }}
