name: "Desktop Build & Release"

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  build-linux:
    name: Build Linux
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
      - name: Install Linux Dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y ninja-build libgtk-3-dev
      - name: Install project dependencies
        run: flutter pub get
      - name: Build Linux
        run: flutter build linux --release
      - name: Archive Linux Build
        run: zip -r linux-build.zip build/linux/x64/release/bundle/
      - name: Upload Linux Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: linux-build
          path: linux-build.zip

  build-windows:
    name: Build Windows
    runs-on: windows-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
      - name: Install project dependencies
        run: flutter pub get
      - name: Build Windows
        run: flutter build windows --release
      - name: Archive Windows Build
        run: Compress-Archive -Path build/windows/x64/runner/Release -DestinationPath windows-build.zip
      - name: Upload Windows Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-build
          path: windows-build.zip

  build-macos:
    name: Build macOS
    runs-on: macos-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
      - name: Install project dependencies
        run: flutter pub get
      - name: Build macOS
        run: flutter build macos --release
      - name: Archive macOS Build
        run: zip -r macos-build.zip build/macos/Build/Products/Release/
      - name: Upload macOS Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: macos-build
          path: macos-build.zip

  release:
    name: Release Desktop Artifacts
    runs-on: ubuntu-latest
    needs: [build-linux, build-windows, build-macos]
    steps:
      - name: Download Linux artifact
        uses: actions/download-artifact@v4
        with:
          name: linux-build
          path: ./builds/
      - name: Download Windows artifact
        uses: actions/download-artifact@v4
        with:
          name: windows-build
          path: ./builds/
      - name: Download macOS artifact
        uses: actions/download-artifact@v4
        with:
          name: macos-build
          path: ./builds/
      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: |
            ./builds/linux-build.zip
            ./builds/windows-build.zip
            ./builds/macos-build.zip
          tag: desktop-v1.0.${{ github.run_number }}
        env:
          GITHUB_TOKEN: ${{ secrets.TRY_EXCELETOR_TOKEN }}
