on:
  pull_request:
    branches:
      - main
      - master
  push:
    branches:
      - main
      - master
      - develop

name: "Build & Release"

jobs:
  # Job per Android
  build-android:
    name: Build Android
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'zulu'  # Puoi usare 'adopt' o 'temurin' se preferisci
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
      - run: flutter pub get
      - run: flutter build apk --release --split-per-abi

      
  # Job per iOS
  build-ios:
    name: Build iOS
    runs-on: macos-latest
    needs: build-android
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
      - run: flutter pub get
      - run: flutter build ios --release --no-codesign
      - run: |
          cd build/ios/iphoneos
          mkdir Payload
          cd Payload
          ln -s ../Runner.app
          cd ..
          zip -r app.ipa Payload
      
  # Job per Windows
  build-windows:
    name: Build Windows
    runs-on: windows-latest
    needs: build-android
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
      - run: flutter pub get
      - run: flutter build windows --release
      
  # Job per macOS
  build-macos:
    name: Build macOS
    runs-on: macos-latest
    needs: build-android
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
      - run: flutter pub get
      - run: flutter build macos --release
      
  # Job per Linux
  build-linux:
    name: Build Linux
    runs-on: ubuntu-latest
    needs: build-android
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
      - run: |
          sudo apt-get update -y
          sudo apt-get install -y ninja-build libgtk-3-dev
      - run: flutter pub get
      - run: flutter build linux --release

  # Job per il rilascio
  release:
    name: Release Artifacts
    runs-on: ubuntu-latest
    needs: [build-android, build-ios, build-windows, build-macos, build-linux]
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Push to Releases
        uses: ncipollo/release-action@v1
        with:
          artifacts: |
            build/app/outputs/apk/release/*,
            build/ios/iphoneos/app.ipa,
            build/windows/Runner.exe, # Sostituisci con il percorso corretto
            build/macos/Runner.app, # Sostituisci con il percorso corretto
            build/linux/Runner, # Sostituisci con il percorso corretto
          tag: v1.0.${{ github.run_number }}
          token: ${{ secrets.TRY_EXCELETOR_TOKEN }}
