on:
  pull_request:
    branches:
      - main
      - master
  push:
    branches:
      - main
      - master
      - develop

name: "Build & Release"

jobs:
  build-android-ios:
    name: Build Android & iOS
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4  # Updated to latest
      - uses: actions/setup-java@v4  # Updated to latest
        with:
          distribution: 'zulu'
          java-version: '17'
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          architecture: x64

      # Build Android APK
      - run: flutter build apk --release --split-per-abi

      # Build iOS IPA
      - run: |
          flutter build ios --no-codesign
          cd build/ios/iphoneos
          mkdir Payload
          cd Payload
          ln -s ../Runner.app
          cd ..
          zip -r app.ipa Payload

  build-linux:
    name: Build Linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4  # Updated to latest
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          architecture: x64

      # Install dependencies for Linux build
      - run: |
          sudo apt-get update -y
          sudo apt-get install -y ninja-build libgtk-3-dev

      # Build Linux
      - run: flutter build linux --release

  release:
    name: Release Artifacts
    runs-on: ubuntu-latest
    needs: [build-android-ios, build-linux]
    steps:
      - uses: actions/checkout@v4  # Updated to latest
      - name: Push to Releases
        uses: ncipollo/release-action@v1
        with:
          artifacts: |
            build/app/outputs/flutter-apk/release/*.apk,
            build/ios/iphoneos/app.ipa,
            build/linux/x64/release/bundle/*
          tag: v1.0.${{ github.run_number }}
          token: ${{ secrets.TRY_EXCELETOR_TOKEN }}
